site_name: Pyrotech

pages:
- Introduction: index.md
- ChangeLog: changelog.md
- Modules: modules.md
- Commands: commands.md
- Dropt Rules: droptrules.md
- Compatibility:
  - Known Issues: knownissues.md
  - Ore Compatibility: orecompat.md
  - Wood Compatibility: woodcompat.md
- Devices:
  - Recipe Inheritance: inheritance.md
  - Drying Racks: dryingracks.md
  - Worktables: worktables.md
  - Refractory Machines: refractorymachines.md
  - Campfire Effects: campfire.md
- Community Scripts:
  - Community Scripts: communityscripts.md
  - Wood:  scripts/wood.md
- ZenScript:
  - Barrel: zs/barrel.md
  - Bellows: zs/bellows.md
  - Bloomery: zs/bloomery.md
  - Brick Crucible: zs/brickcrucible.md
  - Brick Faucet: zs/faucetbrick.md
  - Brick Kiln: zs/brickkiln.md
  - Brick Oven: zs/brickoven.md
  - Brick Sawmill: zs/bricksawmill.md
  - Brick Tank: zs/bricktank.md
  - Burn: zs/burn.md
  - Campfire: zs/campfire.md
  - Chopping Block: zs/chopping.md
  - Compacting Bin: zs/compactingbin.md
  - Compost Bin: zs/compostbin.md
  - Crate: zs/crate.md
  - Crude Drying Rack: zs/crudedryingrack.md
  - Drying Rack: zs/dryingrack.md
  - Durable Crate: zs/durablecrate.md
  - Durable Rock Bag: zs/durablerockbag.md
  - Durable Shelf: zs/durableshelf.md
  - Durable Stash: zs/durablestash.md
  - Granite Anvil: zs/graniteanvil.md
  - Ironclad Anvil: zs/ironcladanvil.md
  - Mechanical Bellows: zs/mechanicalbellows.md
  - Mechanical Compactor: zs/mechanicalcompactor.md
  - Mechanical Hopper: zs/mechanicalhopper.md
  - Mechanical Mulcher: zs/mechanicalmulcher.md
  - Pit Kiln: zs/pitkiln.md
  - Shelf: zs/shelf.md
  - Simple Rock Bag: zs/simplerockbag.md
  - Soaking Pot: zs/soakingpot.md
  - Stages: zs/stages.md
  - Stash: zs/stash.md
  - Stone Crucible: zs/stonecrucible.md
  - Stone Faucet: zs/faucetstone.md
  - Stone Kiln: zs/stonekiln.md
  - Stone Oven: zs/stoneoven.md
  - Stone Sawmill: zs/stonesawmill.md
  - Stone Tank: zs/stonetank.md
  - Wood Rack: zs/woodrack.md
  - Worktable: zs/worktable.md
- Development:
  - Contributor's License Agreement: cla.md

theme: readthedocs

extra_css: [custom.css]

markdown_extensions:
- admonition
#- attr_list
- codehilite
